---
# tasks file for nginx
- name: update debian
  apt:
    update_cache=yes
- name: desinstallation apache2
  apt:
    name: apache2
    state: absent
- name: installation nginx
  apt:
    name: nginx
    state: present
- name: restart and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Suppression default
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: service nginx

- name: Installation php
  include: php.yml

- name: configurations des sites
  include: sites.yml
  with_items: "{{ domains }}"