---
- name: Installation php
  apt: name= {{ item }} state=present
  with_items: php_package

- lineinfile: 
    path: /etc/php/7.0/fpm/php.ini 
    regexp: 'upload_max_filesize[\s]?=' 
    line: 'upload_max_filesize= {{ php_upload_max_filesize }}'

- lineinfile: 
    path: /etc/php/7.0/fpm/php.ini 
    regexp: 'post_max_size[\s]?=' 
    line: 'post_max_size= {{ php_post_max_size }}'

- lineinfile: 
    path: /etc/php/7.0/fpm/php.ini 
    regexp: 'memory_limit[\s]?=' 
    line: 'memory_limit= {{ php_memory_limit }}'

- lineinfile: 
    path: /etc/php/7.0/fpm/php.ini 
    regexp: 'date.timezone[\s]?=' 
    line: 'date.timezone= {{ php_date_timezone }}'


  notify: service php
    
