---
- hosts: Debian
  vars:
    user: dev
    domains: 
     - domain: local.dev
       php: yes
     - domain: marc.org
       php: no
       repo: https://github.com/orochigaya/Web
  tasks:
  roles:
    - nginx
    - user
    - tools