---
- hosts: Debian
  vars:
    user: dev
    domains: 
     - domain: local.dev
       php: yes
     - domain: marc.org
       php: no
       repo: https://github.com/Grafikart/grafikart.github.io.git
  tasks:
  roles:
    - nginx
    - user
    - tools