---
# tasks file for rancher
- name: Create a data container
  docker_container:
    name: rancher
    image: rancher/rancher
    ports:
      - 7000:80
      - 7443:443
    state: started
    restart: yes